import { createFileRoute } from "@tanstack/react-router";
import { ShieldCheck, Lock, UserX, Sparkles } from "lucide-react";

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

export const Route = createFileRoute("/about")({
  head: () => ({
    meta: [
      { title: "About — WorkFlow AI" },
      {
        name: "description",
        content:
          "WorkFlow AI helps professionals improve productivity with AI-powered email writing, scheduling, and workplace assistance. No accounts. No data stored.",
      },
      { property: "og:title", content: "About WorkFlow AI" },
      {
        property: "og:description",
        content: "AI productivity tools for professionals. No accounts, no data stored.",
      },
    ],
  }),
  component: About,
});

function About() {
  return (
    <div className="mx-auto w-full max-w-3xl px-4 py-10 sm:px-6">
      <div className="inline-flex items-center gap-2 rounded-full bg-primary/10 px-3 py-1 text-xs font-medium text-primary">
        <Sparkles className="h-3.5 w-3.5" /> About
      </div>
      <h2 className="mt-4 text-3xl font-semibold tracking-tight">Productivity, powered by AI.</h2>
      <p className="mt-4 text-muted-foreground">
        WorkFlow AI is a lightweight web app that helps professionals get more done. It offers three focused
        tools — a Smart Email Generator, an AI Task Planner, and an AI Workplace Assistant — designed to
        support your day-to-day communication, planning, and organisation.
      </p>
      <p className="mt-3 text-muted-foreground">
        Everything works instantly in your browser. There are <strong>no accounts</strong>, no sign-up, and{" "}
        <strong>no personal information or data is stored</strong>. Your inputs are sent to the AI model to
        generate a response, and that's it — nothing is kept afterwards.
      </p>

      <div className="mt-8 grid gap-4 sm:grid-cols-3">
        <Card>
          <CardHeader>
            <UserX className="h-5 w-5 text-primary" />
            <CardTitle className="text-base">No accounts</CardTitle>
            <CardDescription>Open the app and start working — no sign-up required.</CardDescription>
          </CardHeader>
        </Card>
        <Card>
          <CardHeader>
            <Lock className="h-5 w-5 text-primary" />
            <CardTitle className="text-base">No data stored</CardTitle>
            <CardDescription>We don't save your inputs, drafts, or chats.</CardDescription>
          </CardHeader>
        </Card>
        <Card>
          <CardHeader>
            <ShieldCheck className="h-5 w-5 text-primary" />
            <CardTitle className="text-base">Responsible AI</CardTitle>
            <CardDescription>Always review AI output before sending or acting on it.</CardDescription>
          </CardHeader>
        </Card>
      </div>

      <Card className="mt-8">
        <CardHeader>
          <CardTitle className="text-base">A note on AI</CardTitle>
        </CardHeader>
        <CardContent className="text-sm text-muted-foreground">
          AI responses are generated by a large language model and may occasionally be inaccurate or
          incomplete. Treat outputs as a helpful starting point, not a final answer. Do not paste confidential
          or personal information you would not want processed by a third-party AI service.
        </CardContent>
      </Card>
    </div>
  );
}
